let currentDate = new Date();
let currentSession = null;
const loginScreen=document.getElementById("loginScreen"),siteApp=document.getElementById("siteApp"),loginForm=document.getElementById("loginForm"),loginEmail=document.getElementById("loginEmail"),loginPassword=document.getElementById("loginPassword"),loginButton=document.getElementById("loginButton"),loginMessage=document.getElementById("loginMessage"),logoutButton=document.getElementById("logoutButton"),calendarTitle=document.getElementById("calendarTitle"),calendarGrid=document.getElementById("calendarGrid"),prevMonthButton=document.getElementById("prevMonth"),nextMonthButton=document.getElementById("nextMonth"),dayPanel=document.getElementById("dayPanel"),closeDayPanelButton=document.getElementById("closeDayPanel"),selectedDateTitle=document.getElementById("selectedDateTitle");
async function checkSession(){const{data,error}=await supabaseClient.auth.getSession();if(error){console.error("세션 확인 오류:",error);showLogin();return}currentSession=data.session;currentSession?showSite():showLogin()}
function showLogin(){loginScreen.classList.remove("hidden");siteApp.classList.add("hidden");dayPanel.classList.remove("open")}
function showSite(){loginScreen.classList.add("hidden");siteApp.classList.remove("hidden");renderCalendar()}
loginForm.addEventListener("submit",async e=>{e.preventDefault();const email=loginEmail.value.trim(),password=loginPassword.value;loginMessage.textContent="";loginButton.disabled=true;loginButton.textContent="로그인 중...";const{data,error}=await supabaseClient.auth.signInWithPassword({email,password});loginButton.disabled=false;loginButton.textContent="로그인";if(error){console.error("로그인 오류:",error);loginMessage.textContent="이메일 또는 비밀번호를 확인해주세요.";return}currentSession=data.session;loginPassword.value="";showSite()});
logoutButton.addEventListener("click",async()=>{await supabaseClient.auth.signOut();currentSession=null;loginPassword.value="";showLogin()});
supabaseClient.auth.onAuthStateChange((event,session)=>{currentSession=session;if(event==="SIGNED_OUT")showLogin()});
function renderCalendar(){calendarGrid.innerHTML="";const year=currentDate.getFullYear(),month=currentDate.getMonth();calendarTitle.textContent=`${year}년 ${month+1}월`;const firstDay=new Date(year,month,1).getDay(),lastDate=new Date(year,month+1,0).getDate(),previousMonthLastDate=new Date(year,month,0).getDate();for(let i=firstDay-1;i>=0;i--)createDayCell(new Date(year,month-1,previousMonthLastDate-i),true);for(let date=1;date<=lastDate;date++)createDayCell(new Date(year,month,date),false);const totalCells=calendarGrid.children.length,remainingCells=totalCells<=35?35-totalCells:42-totalCells;for(let date=1;date<=remainingCells;date++)createDayCell(new Date(year,month+1,date),true)}
function createDayCell(date,otherMonth){const day=document.createElement("div");day.classList.add("calendar-day");if(otherMonth)day.classList.add("other-month");const weekday=date.getDay();if(weekday===0)day.classList.add("sunday");if(weekday===6)day.classList.add("saturday");const today=new Date(),isToday=date.getFullYear()===today.getFullYear()&&date.getMonth()===today.getMonth()&&date.getDate()===today.getDate();if(isToday)day.classList.add("today");const dayNumber=document.createElement("div");dayNumber.className="day-number";dayNumber.textContent=date.getDate();day.appendChild(dayNumber);day.addEventListener("click",()=>openDayPanel(date));calendarGrid.appendChild(day)}
function openDayPanel(date){const weekdayNames=["일요일","월요일","화요일","수요일","목요일","금요일","토요일"];selectedDateTitle.textContent=`${date.getFullYear()}. ${date.getMonth()+1}. ${date.getDate()}. ${weekdayNames[date.getDay()]}`;dayPanel.classList.add("open")}
function closeDayPanel(){dayPanel.classList.remove("open")}
prevMonthButton.addEventListener("click",()=>{currentDate=new Date(currentDate.getFullYear(),currentDate.getMonth()-1,1);renderCalendar()});
nextMonthButton.addEventListener("click",()=>{currentDate=new Date(currentDate.getFullYear(),currentDate.getMonth()+1,1);renderCalendar()});
closeDayPanelButton.addEventListener("click",closeDayPanel);
checkSession();
